#-------------------------------
# General Site Settings

title: Kol70
description: "Food Blogging"
baseurl: "/kol70" # the subpath of your site, e.g. /blog
url: "https://rajwrita.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Rajwrita Nath
author-avatar: rajwrita.png


#-------------------------------
# Contact links
facebook:  https://www.facebook.com/rajwrita # Add your Facebook handle
twitter:   https://twitter.com/rajwrita # Add your Facebook handle
instagram: https://www.instagram.com/rajwrita/ # Add your Facebook handle
linkedin: https://www.linkedin.com/in/rajwrita-nath/ # Add your Facebook handle
google: https://www.google.com/search?hl=en-IN&sxsrf=ALeKk01YCsiS703fYy1XueqjQkyTojhlRw%3A1586438982605&ei=RiOPXsDEJIXl9QPZ2qHADw&q=Rajwrita+Nath&oq=Rajwrita+Nath&gs_lcp=CgZwc3ktYWIQAzoECCMQJzoHCCMQ6gIQJzoECAAQQzoFCAAQkQI6BQgAEIMBOgIIADoHCAAQFBCHAjoECAAQDToGCAAQDRAeOggIABAIEA0QHkotCBcSKTBnMjU4ZzI2NWcyNjFnMjYwZzM2NWczNzZnMjY0ZzIzN2cyMTZnMjM2ShkIGBIVMGcxZzFnMWcxZzFnMWcxZzFnMWc5UO4iWPBkYOBwaAFwAHgAgAH0AogBtiOSAQYyLTE2LjKYAQCgAQGqAQdnd3Mtd2l6sAEK&sclient=psy-ab&ved=0ahUKEwjA_4_gudvoAhWFcn0KHVltCPgQ4dUDCAw&uact=5


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: gmail.us19.list-manage.com/subscribe/post?u=6fa46918fab6116872c1dfd84&amp;id=b5e1063bca
# Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
